services:
  # PostgreSQL database service
  db:
    image: postgres
    container_name: r_stock_analyzer_db
    environment:
      POSTGRES_USER: your_psql_username
      POSTGRES_PASSWORD: your_psql_pwd
      POSTGRES_DB: r_stock_analyzer
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

volumes:
  db_data:
    driver: local